import type { NextPage } from 'next'
import Head from 'next/head'

function funcao_pdf() {
  var pegar_dados = document.getElementById('dados')?.innerHTML;
  
  var janela = window.open('', '', 'width=800, heigtht=600');
  janela?.document.write('<html><head>');
  janela?.document.write('<title>PDF<title></head>');
  janela?.document.write('<body');
  janela?.document.write(pegar_dados);
  janela?.document.write('</boby>');
  janela?.document.write('</html>');
  janela?.document.close();
  janela?.print();
}
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Gerar PFF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1>Teste poc api:</h1>
      <div id="dados">
        <p>Nome: mohamed</p>
        <p>Nome: mohamed</p>
        <p>Nome: mohamed</p>
        <p>Nome: mohamed</p>
      </div>
        <button type="button" onClick={() => funcao_pdf()}>Baixar PDF</button>
    </div>
  )
}

export default Home
