import type { NextPage } from 'next'
import Head from 'next/head'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import download from 'downloadjs';

async function  funcao_pdf() {
 const pdfDoc = await PDFDocument.create()
  const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman)

  const page = pdfDoc.addPage()
  const {  height } = page.getSize()
  const fontSize = 30
  page.drawText('pdf criado!!!!!', {
    x: 50,
    y: height - 4 * fontSize,
    size: fontSize,
    font: timesRomanFont,
    color: rgb(0, 0.53, 0.71),
  })

  const pdfBytes = await pdfDoc.save()

	download(pdfBytes, "Exemplo.pdf", "application/pdf");
	
}
const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Gerar PFF</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<h1>Teste - api:</h1>
			
			<button type="button" onClick={() => funcao_pdf()}>Gerar PDF</button>
		</div>
	)
}

export default Home
